import Head from 'next/head';
import React, { useEffect } from 'react';
import { useSelector } from 'react-redux';
import { useRouter } from 'next/router';
import Tablero from '../components/admin/tablero/indexTablero';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Tablero {...props} />
    </>
  );
}

Home.auth = {
  role: 'Admin'
};

const urlControlSelector = {
  ordenes: true,
  productos: true,
  clientes: true
};
const urlControlSelectorCaja = {
  ingresos: true,
  egresos: true
};

export const getServerSideProps = async (ctx) => {
  const use = ctx.query.use || false;
  let selector = ctx.query.s?.toLocaleLowerCase();
  const selectorCaja = ctx.query.sc?.toLocaleLowerCase();
  const idcajaURL = ctx.query.idc?.toLocaleLowerCase();
  if ((!use && !selector) || !urlControlSelector[selector]) {
    return {
      redirect: {
        permanent: false,
        destination: '/admin?s=ordenes&sc=ingresos'
      },
      props: {}
    };
  }

  if (selectorCaja && !urlControlSelectorCaja[selectorCaja]) {
    return {
      redirect: {
        permanent: false,
        destination: '/admin?s=ordenes&sc=ingresos'
      },
      props: {}
    };
  }

  if (urlControlSelectorCaja[selectorCaja]) selector = selectorCaja;
  return {
    props: {
      use,
      selector: selector,
      idcajaURL: idcajaURL || null
    }
  };
};
